export const leads = [
  {
    id: "1",
    status: "Hot",
    name: "James Whitfield",
    initials: "JW",
    email: "j.whitfield@gmail.com",
    phone: "+61 412 345 678",
    property: "32 Ocean Parade, Brighton",
    suburb: "Brighton, VIC",
    budget: "$3.0M – $3.5M",
    price: "$3,200,000",
    requested: "Section 32",
    time: "2m ago",
    captured: "Apr 13, 2026 – 9:15AM",
  },
  {
    id: "2",
    status: "Warm",
    name: "Priya Sharma",
    initials: "PS",
    email: "priya.s@outlook.com",
    phone: "+61 423 456 789",
    property: "14A Collins St, Melbourne CBD",
    suburb: "Melbourne CBD, VIC",
    budget: "$1.7M – $2.0M",
    price: "$1,850,000",
    requested: "Contract",
    time: "18m ago",
    captured: "Apr 13, 2026 – 9:00AM",
  },
  {
    id: "3",
    status: "Hot",
    name: "Marcus Chen",
    initials: "MC",
    email: "marcus.chen@icloud.com",
    phone: "+61 434 567 890",
    property: "7 Hillcrest Ave, Toorak",
    suburb: "Toorak, VIC",
    budget: "$5.5M – $6.2M",
    price: "$5,800,000",
    requested: "Floor Plan",
    time: "1h ago",
    captured: "Apr 13, 2026 – 8:20AM",
  },
  {
    id: "4",
    status: "New",
    name: "Sophie Laurent",
    initials: "SL",
    email: "sophie.l@gmail.com",
    phone: "+61 445 678 901",
    property: "55 Bay Rd, St Kilda",
    suburb: "St Kilda, VIC",
    budget: "$1.9M – $2.2M",
    price: "$2,100,000",
    requested: "Section 32",
    time: "3h ago",
    captured: "Apr 13, 2026 – 6:30AM",
  },
  {
    id: "5",
    status: "Warm",
    name: "Daniel Kim",
    initials: "DK",
    email: "d.kim@gmail.com",
    phone: "+61 456 789 012",
    property: "Penthouse, 200 Spencer St",
    suburb: "Melbourne CBD, VIC",
    budget: "$4.0M – $5.0M",
    price: "$4,500,000",
    requested: "Contract",
    time: "5h ago",
    captured: "Apr 12, 2026 – 4:10PM",
  },
  {
    id: "6",
    status: "Cold",
    name: "Amelia Torres",
    initials: "AT",
    email: "a.torres@hotmail.com",
    phone: "+61 467 890 123",
    property: "9 Bayside Blvd, Elwood",
    suburb: "Elwood, VIC",
    budget: "$1,500/wk – $1,800/wk",
    price: "$1,650/wk",
    requested: "Rental Form",
    time: "1d ago",
    captured: "Apr 12, 2026 – 10:00AM",
  },
  {
    id: "7",
    status: "New",
    name: "Noah Williams",
    initials: "NW",
    email: "noah.w@gmail.com",
    phone: "+61 478 901 234",
    property: "22 Park Lane, South Yarra",
    suburb: "South Yarra, VIC",
    budget: "$2.5M – $3.0M",
    price: "$2,750,000",
    requested: "Section 32",
    time: "1d ago",
    captured: "Apr 12, 2026 – 9:00AM",
  },
  {
    id: "8",
    status: "Warm",
    name: "Isabella Moore",
    initials: "IM",
    email: "i.moore@gmail.com",
    phone: "+61 489 012 345",
    property: "44 Chapel St, Windsor",
    suburb: "Windsor, VIC",
    budget: "$900/wk – $1,100/wk",
    price: "$980/wk",
    requested: "Rental Form",
    time: "2d ago",
    captured: "Apr 11, 2026 – 3:45PM",
  },
];
